
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

language: scala

scala:
   - 2.11.8

jdk: oraclejdk8

script:
  - sbt test

before_script:
  - mysql -uroot -e 'create database playunittest; create database test;'
  # Clone generated docs so that we can run some integration tests
  - git clone https://github.com/playframework/play-generated-docs.git $PWD/data/generated
